# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractFormData(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.FinalFormInformations:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractFormData", llm_response=llm_response, mode="request")
        return typing.cast(types.FinalFormInformations, result)

    def ExtractFormDataGen(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractFormDataGen", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def ExtractFormDataStreamed(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractFormDataStreamed", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def TextClassification(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClassificationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TextClassification", llm_response=llm_response, mode="request")
        return typing.cast(types.ClassificationResult, result)

    def TextClassification_ci(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClassificationResult_ci:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TextClassification_ci", llm_response=llm_response, mode="request")
        return typing.cast(types.ClassificationResult_ci, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractFormData(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.FinalFormInformations:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractFormData", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.FinalFormInformations, result)

    def ExtractFormDataGen(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractFormDataGen", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def ExtractFormDataStreamed(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractFormDataStreamed", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def TextClassification(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClassificationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TextClassification", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClassificationResult, result)

    def TextClassification_ci(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClassificationResult_ci:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TextClassification_ci", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClassificationResult_ci, result)

    