# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def ExtractFormData(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.FinalFormInformations:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractFormData", args={
            "text": text,
        })
        return typing.cast(types.FinalFormInformations, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractFormDataGen(self, input: types.TextInputGen,
        baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractFormDataGen", args={
            "input": input,
        })
        return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractFormDataStreamed(self, input: types.TextInputStreamed,
        baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractFormDataStreamed", args={
            "input": input,
        })
        return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def TextClassification(self, text: str,themes: typing.List["types.Theme"],
        baml_options: BamlCallOptions = {},
    ) -> types.ClassificationResult:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="TextClassification", args={
            "text": text,"themes": themes,
        })
        return typing.cast(types.ClassificationResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def TextClassification_ci(self, text: str,themes: typing.List["types.Theme_ci"],
        baml_options: BamlCallOptions = {},
    ) -> types.ClassificationResult_ci:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="TextClassification_ci", args={
            "text": text,"themes": themes,
        })
        return typing.cast(types.ClassificationResult_ci, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractFormData(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.FinalFormInformations, types.FinalFormInformations]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractFormData", args={
            "text": text,
        })
        return baml_py.BamlSyncStream[stream_types.FinalFormInformations, types.FinalFormInformations](
          result,
          lambda x: typing.cast(stream_types.FinalFormInformations, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FinalFormInformations, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractFormDataGen(self, input: types.TextInputGen,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractFormDataGen", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractFormDataStreamed(self, input: types.TextInputStreamed,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractFormDataStreamed", args={
            "input": input,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def TextClassification(self, text: str,themes: typing.List["types.Theme"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ClassificationResult, types.ClassificationResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="TextClassification", args={
            "text": text,"themes": themes,
        })
        return baml_py.BamlSyncStream[stream_types.ClassificationResult, types.ClassificationResult](
          result,
          lambda x: typing.cast(stream_types.ClassificationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClassificationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def TextClassification_ci(self, text: str,themes: typing.List["types.Theme_ci"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ClassificationResult_ci, types.ClassificationResult_ci]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="TextClassification_ci", args={
            "text": text,"themes": themes,
        })
        return baml_py.BamlSyncStream[stream_types.ClassificationResult_ci, types.ClassificationResult_ci](
          result,
          lambda x: typing.cast(stream_types.ClassificationResult_ci, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClassificationResult_ci, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractFormData(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractFormData", args={
            "text": text,
        }, mode="request")
        return result
    def ExtractFormDataGen(self, input: types.TextInputGen,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractFormDataGen", args={
            "input": input,
        }, mode="request")
        return result
    def ExtractFormDataStreamed(self, input: types.TextInputStreamed,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractFormDataStreamed", args={
            "input": input,
        }, mode="request")
        return result
    def TextClassification(self, text: str,themes: typing.List["types.Theme"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="TextClassification", args={
            "text": text,"themes": themes,
        }, mode="request")
        return result
    def TextClassification_ci(self, text: str,themes: typing.List["types.Theme_ci"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="TextClassification_ci", args={
            "text": text,"themes": themes,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractFormData(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractFormData", args={
            "text": text,
        }, mode="stream")
        return result
    def ExtractFormDataGen(self, input: types.TextInputGen,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractFormDataGen", args={
            "input": input,
        }, mode="stream")
        return result
    def ExtractFormDataStreamed(self, input: types.TextInputStreamed,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractFormDataStreamed", args={
            "input": input,
        }, mode="stream")
        return result
    def TextClassification(self, text: str,themes: typing.List["types.Theme"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="TextClassification", args={
            "text": text,"themes": themes,
        }, mode="stream")
        return result
    def TextClassification_ci(self, text: str,themes: typing.List["types.Theme_ci"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="TextClassification_ci", args={
            "text": text,"themes": themes,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))