# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ClassificationResult": types.ClassificationResult,
    "stream_types.ClassificationResult": stream_types.ClassificationResult,

    "types.ClassificationResult_ci": types.ClassificationResult_ci,
    "stream_types.ClassificationResult_ci": stream_types.ClassificationResult_ci,

    "types.ContactInfo": types.ContactInfo,
    "stream_types.ContactInfo": stream_types.ContactInfo,

    "types.FinalFormInformations": types.FinalFormInformations,
    "stream_types.FinalFormInformations": stream_types.FinalFormInformations,

    "types.PersonalInfo": types.PersonalInfo,
    "stream_types.PersonalInfo": stream_types.PersonalInfo,

    "types.TextInput": types.TextInput,
    "stream_types.TextInput": stream_types.TextInput,

    "types.TextInputGen": types.TextInputGen,
    "stream_types.TextInputGen": stream_types.TextInputGen,

    "types.TextInputStreamed": types.TextInputStreamed,
    "stream_types.TextInputStreamed": stream_types.TextInputStreamed,

    "types.Theme": types.Theme,
    "stream_types.Theme": stream_types.Theme,

    "types.Theme_ci": types.Theme_ci,
    "stream_types.Theme_ci": stream_types.Theme_ci,


}